USE ROLE ACCOUNTADMIN;

-- --------------------------------------------------
-- Role: SITE_SAFETY_APP_ROLE
-- Purpose: Scoped access for Site Safety Streamlit app
-- --------------------------------------------------
CREATE ROLE IF NOT EXISTS SITE_SAFETY_APP_ROLE;

-- Database & schema access
GRANT USAGE ON DATABASE SNOWFLAKE_LEARNING_DB
    TO ROLE SITE_SAFETY_APP_ROLE;

GRANT USAGE ON SCHEMA SNOWFLAKE_LEARNING_DB.PUBLIC
    TO ROLE SITE_SAFETY_APP_ROLE;

-- Image stage access
GRANT READ, WRITE ON STAGE SNOWFLAKE_LEARNING_DB.PUBLIC.SAFETY_IMG_STG
    TO ROLE SITE_SAFETY_APP_ROLE;

-- History tables access
GRANT SELECT, INSERT ON TABLE SNOWFLAKE_LEARNING_DB.PUBLIC.SITE_HAZARD_HISTORY
    TO ROLE SITE_SAFETY_APP_ROLE;

GRANT SELECT, INSERT ON TABLE SNOWFLAKE_LEARNING_DB.PUBLIC.SITE_RISK_HISTORY
    TO ROLE SITE_SAFETY_APP_ROLE;

-- Email notification integration
GRANT USAGE ON INTEGRATION SITE_EMAIL_INT
    TO ROLE SITE_SAFETY_APP_ROLE;